### ISSUE TITLE
No PASS reports since 2015-08-06

### ISSUE THREAD

**Issue by eserte** [alnewkirk/Emailesque#7]
See http://fast-matrix.cpantesters.org/?dist=Emailesque;reports=1#sl=7,1 for a datetime sorted overview of test reports. Statistical analysis says that the failures may be caused by Data::Object 0.31, see http://analysis.cpantesters.org/solved?distv=Emailesque-1.23#mod%3AData%3A%3AObject

**Comment by alnewkirk** [comment]
Hey Slaven,

Thanks for pointing this out. I'm going to take care of it this week. I'll
update you once this has been resolved.

Thanks again,

Al

**Comment by alnewkirk** [comment]
Sorry for the delayed response. This has since been resolved, closing this ticket.
